#!/usr/bin/env sh

./2018/1/1.sh 2018/1/input.txt
./2018/1/2.sh 2018/1/input.txt
echo -n "2.1: "
./2018/2/checksum.lua 2018/2/input.txt
echo -n "2.2: "
./2018/2/boxes.lua 2018/2/input.txt
echo -n "3.1: "
./2018/3/overlapping.py 2018/3/input.txt
echo -n "3.2: "
./2018/3/intact.py 2018/3/input.txt
java 2018/4/Strategy1.java 2018/4/input.txt
cc 2018/5/polymer.c && ./a.out 2018/5/input.txt
rustc 2018/7/sleigh.rs && ./sleigh 2018/7/input.txt
